name: Get iTop Tarball

on: 
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull supervisions/itop:latest

      - name: Save Image to Tar
        run: docker save supervisions/itop:latest -o itop_latest.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: itop-docker-image
          path: itop_latest.tar
          retention-days: 1 # 文件仅保留1天，节省空间
